project:
  type: website
  output-dir: docs 

website:
  title: "Viviana Ugalde"
  navbar:
    background: dark
    left:
      - text: "Home"
        file: index.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Skills"
        file: skills.qmd
      - text: "Contact"
        file: contact.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true